version: '3.7'

services:

  wordpress:
    image: wordpress
    depends_on:
      - mysql
    restart: always
    ports:
      - "80:80"
      - "443:443"
    environment:
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        define( 'SAVEQUERIES', true );
        define( 'SCRIPT_DEBUG', true );
        define( 'CONCATENATE_SCRIPTS', false );
        define( 'JETPACK_DEV_DEBUG', true );
    volumes:
      - ./html/:/var/www/html/
      # - ../svn/trunk/:/var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}/
      - ./dist/:/var/www/html/wp-content/plugins/${COMPOSE_PROJECT_NAME}/
      - ./ssl/localhost.crt:/etc/apache2/ssl/localhost.crt
      - ./ssl/localhost.key:/etc/apache2/ssl/localhost.key
      - ./ssl/000-default.conf:/etc/apache2/sites-enabled/000-default.conf
      - ./ssl/ssl.load:/etc/apache2/mods-enabled/ssl.load
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini

  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
      MYSQL_DATABASE: wordpress

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD
    volumes:
      - ./uploads.ini:/usr/local/etc/php/php.ini

volumes:
  data:
