version: '3'

services:

  mysql:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - ./initdb:/docker-entrypoint-initdb.d
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

  wordpress:
    image: wordpress:$WP_IMAGE_VERSION
    depends_on:
      - mysql
    restart: always
    ports:
      - 80:80
    environment:
      WORDPRESS_DB_PASSWORD: $DB_PASSWORD
      WORDPRESS_DEBUG: 1
      WORDPRESS_CONFIG_EXTRA: |
        define( 'WP_DEBUG_DISPLAY', false );
        define( 'WP_DEBUG_LOG', true );
        define( 'SAVEQUERIES', true );
    volumes:
      - ./html/:/var/www/html/
      - ./dist/:/var/www/html/wp-content/plugins/$PLUGIN_SLUG/

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    depends_on:
      - mysql
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: $DB_PASSWORD

volumes:
  database:
